apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: glimpse-service-chat
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: glimpse-service-chat
    spec:
      containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "-p", "8081",
          "-a", "127.0.0.1:5000",
          "-s", "chat.glimpse.online",
          "-v", "2017-08-26r1",
        ]
        ports:
          - containerPort: 8081
      - name: chat
        image: gcr.io/glimpse-123456/glimpse-service-chat:latest
        ports:
          - containerPort: 5000
        volumeMounts:
        - name: credentials-volume
          mountPath: /secrets/google_credentials
          readOnly: true
        env:
        - name: CASSANDRA_HOSTS
          value: cassandra
        - name: GLIMPSE_SERVICE_ASSET
          value: http://glimpse-service-asset # internal name for the service
        - name: CHAT_CREATED_TOPIC
          value: chat-created
        - name: GOOGLE_INTERNAL_API_CREDENTIALS
          value: /secrets/google_credentials/internal-credentials.json

      volumes:
      - name: credentials-volume
        secret:
          secretName: internal-api-credentials
